# Generated by Django 4.2.6 on 2023-10-24 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('term', 'reading', 'tags', 'ruleIdentifiers', 'definitions')},
        ),
    ]
