# Generated by Django 4.2.6 on 2023-10-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_alter_dictionary_title_alter_term_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('term', 'reading', 'definitions', 'dictionary')},
        ),
    ]
