# Generated by Django 4.2.6 on 2023-10-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_alter_term_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('term', 'reading', 'tags', 'ruleIdentifiers', 'popularity', 'definitions', 'sequence', 'dictionary'), name='uniq'),
        ),
    ]
